### PR TITLE
Update language-mapping-list.js

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ScottDowne** [comment]
@gideonthomas stumped on this PR and asked me what it was about, and I didn't remember.

I had to look it up, but this was failing when used while running karma. This fixed it.

I ended up with a workaround where my test would instead pass faked data, and not actually require this in.

**Comment by alicoding** [comment]
I couldn't get this to fail on Karma testrunner... Couldn't you give an example of how to make it fail? since this is working fine for me when I import it using Karma.

**Comment by ScottDowne** [comment]
It's very likely there is more to it. Either way checking that root is
defined before blindly using it cannot hurt? The fact it fixes a case is
only a bonus.

**Comment by alicoding** [comment]
I agree that it doesn't hurt, but it can cause other problem such as falling into other condition like going into `else`.

**Comment by ScottDowne** [comment]
I suspect the else if is very likely to succeed. If root is undefined the
first condition is guaranteed to fail. I'll take that trade. If you're
interested in a closer look I can get a branch to a repo that's in a
failing case so you can test.

**Comment by alicoding** [comment]
Yes please. I would love to further investigate this since checking and failing later is only fixing half of the problem here...

**Comment by ScottDowne** [comment]
This branch is still failing for me:

https://github.com/ScottDowne/donate.mozilla.org/tree/test-fail-case

Key change is in: https://github.com/mozilla/donate.mozilla.org/compare/master...ScottDowne:test-fail-case?expand=1

just run `npm run test` and should fail with root is undefined.

Ignore the currency stuff, that's failing for me and it's new and unrelated, and would just confuse the errors.

I'm fixing that in another unrelated patch.

**Comment by alicoding** [comment]
Weird thing is that I only get those 6 errors, but that `root is undefined`? I don't know if it's version of node or node_modules outdated on your machine? but I don't get that?

**Comment by ScottDowne** [comment]
I removed the currency errors in that patch, so you shouldn't be seeing any. There was only two anyway, not six.

**Comment by ScottDowne** [comment]
Node is version 6.8.0 and node_modules was cleared.

**Comment by ScottDowne** [comment]
If you're curious as to what it looks like:

fail

You probably need to look very close if you have other errors.

**Comment by ScottDowne** [comment]
If you want want to boil the logic down, `module.exports = factory();` should be the last case. Like this:

```
  if (root) {
    if (typeof define === 'function' && define.amd) {
      define(function() {
        return (root.languageMappingList = factory());
      });
    } else {
      root.languageMappingList = factory();
    }
  } else {
    module.exports = factory();
  }
```

**Comment by alicoding** [comment]
I just skip those errors and now it's only failing on this one?

```
FAILED TESTS:
  location-parser.js
    ✖ valid locale, but we don' currently support it.
      Firefox 50.0.0 (Mac OS X 10.12.0)
    expected Object { locale: 'en-US', redirect: '/fa-KE/thank-you/' } deepEqual Object { locale: 'en-US', redirect: '/thank-you/' }
    @/Users/alialdallal/projects/donate.mozilla.org/tests/react/index.jsx:44189:8
```

I couldn't find that `typeError: root is undefined` anywhere... I suspect this could be version of phantomjs, or Firefox on Fedora specific issue or something...

I need to find a way to run this on similar platform... 

These are the version of Karma that's installed on my node_modules

```
├── karma-firefox-launcher@0.1.7
├── karma-mocha@0.2.1
├── karma-mocha-reporter@1.1.5
├── karma-sourcemap-loader@0.3.6
├─┬ karma-webpack@1.7.0
```

**Comment by ScottDowne** [comment]
You on a Mac still right?

I could find other systems to test on and see if it's system related or not too.

**Comment by alicoding** [comment]
Yep, I'm on Mac.

**Comment by ScottDowne** [comment]
This is the version I have for everything Karma related:

```
├─┬ karma@0.13.19 
├─┬ karma-chrome-launcher@0.2.2 
├─┬ karma-coverage@0.5.3 
├─┬ karma-coveralls@1.1.2 
├── karma-firefox-launcher@0.1.7 
├── karma-mocha@0.2.1 
├── karma-mocha-reporter@1.1.5 
├── karma-sourcemap-loader@0.3.6 
├─┬ karma-webpack@1.7.0 
```

My last 5 match your five.

**Comment by ScottDowne** [comment]
Yeah, not sure how, but pretty sure it's system related. Because, with my langmap patch I get the same error as you.

**Comment by ScottDowne** [comment]
Yeah, you can ignore that failing test too. It's failing because the previous faked langmap had a fake locale in it, which that test expected. See:

```
{
  'en-US': {
    nativeName: "English (US)",
    englishName: "English (US)"
  },
  'de': {
    nativeName: "Deutsch",
    englishName: "German"
  },
  'fa-KE': {
    nativeName: "Fake locale",
    englishName: "Fake locale"
  }
}
```

**Comment by ScottDowne** [comment]
Another question about the logic.

What if there is a case where both the first two conditions are true (as they are in karma)

Why prioritize the `define` block over the `module.exports` block? Isn't `module.exports` ideal? Wouldn't this be the optimal priority?

```
  if (typeof exports === 'object') {
    module.exports = factory();
  } else if (typeof define === 'function' && define.amd) {
    define(function() {
      return (root.languageMappingList = factory());
    });
  } else {
    root.languageMappingList = factory();
  }
```

**Comment by ScottDowne** [comment]
For what it's worth, even if we do figure this out, I still the the logic can be optimized.

Technically my issue has nothing to do with `root`, it's `this` is undefined for me in the global context of language-mapping-list.js

**Comment by ScottDowne** [comment]
That makes sense to me.

Question, so I can better search the error. What is `this` on your end? For me it's undefined all the way to tests/react/index.jsx

**Comment by alicoding** [comment]
It's an object (not on my computer ATM, but will paste if that'll helps)

**Comment by ScottDowne** [comment]
I just searched Karma github issues for the error, and updated everything Krama related. Nothing about my issue. So it's likely it's not common or only. It also means they are not aware of it so figuring out how to reproduce it might be valuable.

And yes, I get that you expect this to be an object, but what's the object for? What does it do? Does it have docs? Is it an empty object?

**Comment by alicoding** [comment]
Interesting enough when I tried to log `root` inside the module I get `undefined` on Firefox console and `{}` on command line interface (terminal) and when I log `this` I get `Window{}` inside terminal and `Window` object on Firefox console.

**Comment by alicoding** [comment]
So I ran `npm run watch:test` and able to get that `root` to throw an error now:

```
Firefox 50.0.0 (Mac OS X 10.12.0) ERROR
  TypeError: root is undefined
  at /Users/alialdallal/projects/donate.mozilla.org/tests/react/index.jsx:44330
```

**Pull request merged**
